"""
Auto-generated by smcheck.testgen for OrderProcessing.

DO NOT edit manually — regenerate with:
  python -m smcheck testgen --output <dir>
"""
from __future__ import annotations

from machine import OrderProcessing



def _active(sm, state_id: str) -> bool:
    """Return True when *state_id* is part of the current active configuration."""
    return any(s.id == state_id for s in sm.configuration)


# ========================================================================
# Top-level path tests (one per top-level path)
# ========================================================================

def test_path_top_01_cancelled():
    """Top-level path 1: idle → cancelled"""
    sm = OrderProcessing(quiet=True)

    sm._dispatched = False
    sm.cancel()

    assert _active(sm, 'cancelled')


def test_path_top_02_cancelled():
    """Top-level path 2: idle → validation → cancelled"""
    sm = OrderProcessing(quiet=True)

    sm.submit()
    sm._dispatched = False
    sm.cancel()

    assert _active(sm, 'cancelled')


def test_path_top_03_cancelled():
    """Top-level path 3: idle → validation → fulfillment → cancelled"""
    sm = OrderProcessing(quiet=True)

    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm._dispatched = False
    sm.cancel()

    assert _active(sm, 'cancelled')


def test_path_top_04_success():
    """Top-level path 4: idle → validation → fulfillment → success"""
    sm = OrderProcessing(quiet=True)

    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm._inventory_allocated = True
    sm._payment_authorized = True
    sm._shipping_acknowledged = True
    sm.complete()

    assert _active(sm, 'success')


def test_path_top_05_failed():
    """Top-level path 5: idle → validation → fulfillment → failed"""
    sm = OrderProcessing(quiet=True)

    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm.fail()

    assert _active(sm, 'failed')


def test_path_top_06_cancelled():
    """Top-level path 6: idle → validation → fulfillment → ops_hold → cancelled"""
    sm = OrderProcessing(quiet=True)

    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm._dispatched = False
    sm._ops_authorized = True
    sm.suspend()
    sm._dispatched = False
    sm.cancel()

    assert _active(sm, 'cancelled')


def test_path_top_07_h():
    """Top-level path 7: idle → validation → fulfillment → ops_hold → h"""
    sm = OrderProcessing(quiet=True)

    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm._dispatched = False
    sm._ops_authorized = True
    sm.suspend()
    sm._ops_authorized = True
    sm.release()



def test_path_top_08_cancelled():
    """Top-level path 8: idle → validation → fulfillment → on_hold → cancelled"""
    sm = OrderProcessing(quiet=True)

    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm._dispatched = False
    sm.pause()
    sm._dispatched = False
    sm.cancel()

    assert _active(sm, 'cancelled')


def test_path_top_09_h():
    """Top-level path 9: idle → validation → fulfillment → on_hold → h"""
    sm = OrderProcessing(quiet=True)

    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm._dispatched = False
    sm.pause()
    sm.resume()



# ========================================================================
# Per-track path tests (one per track path)
# ========================================================================

def test_path_track_inventory_01_allocated():
    """Track 'inventory' path 1: checking → partial_stock → allocated"""
    sm = OrderProcessing(quiet=True)

    # Common preamble
    sm.submit()
    sm.approve()
    sm.start()
    sm.mark_partial()
    sm.accept_partial()

    assert sm._inventory_reserved
    assert sm._inventory_allocated


def test_path_track_inventory_02_out_of_stock():
    """Track 'inventory' path 2: checking → backordered → stock_review → out_of_stock"""
    sm = OrderProcessing(quiet=True)

    # Common preamble
    sm.submit()
    sm.approve()
    sm.start()
    sm.backorder()
    sm.request_approval()
    sm.decline_partial()



def test_path_track_inventory_03_out_of_stock():
    """Track 'inventory' path 3: checking → backordered → stock_review → reserved → out_of_stock"""
    sm = OrderProcessing(quiet=True)

    # Common preamble
    sm.submit()
    sm.approve()
    sm.start()
    sm.backorder()
    sm.request_approval()
    sm.approve_partial()
    sm.mark_unavailable()



def test_path_track_inventory_04_allocated():
    """Track 'inventory' path 4: checking → backordered → stock_review → reserved → allocated"""
    sm = OrderProcessing(quiet=True)

    # Common preamble
    sm.submit()
    sm.approve()
    sm.start()
    sm.backorder()
    sm.request_approval()
    sm.approve_partial()
    sm.allocate()

    assert sm._inventory_reserved
    assert sm._inventory_allocated


def test_path_track_inventory_05_out_of_stock():
    """Track 'inventory' path 5: checking → backordered → reserved → out_of_stock"""
    sm = OrderProcessing(quiet=True)

    # Common preamble
    sm.submit()
    sm.approve()
    sm.start()
    sm.backorder()
    sm.stock_available()
    sm.mark_unavailable()



def test_path_track_inventory_06_allocated():
    """Track 'inventory' path 6: checking → backordered → reserved → allocated"""
    sm = OrderProcessing(quiet=True)

    # Common preamble
    sm.submit()
    sm.approve()
    sm.start()
    sm.backorder()
    sm.stock_available()
    sm.allocate()

    assert sm._inventory_reserved
    assert sm._inventory_allocated


def test_path_track_inventory_07_out_of_stock():
    """Track 'inventory' path 7: checking → reserved → out_of_stock"""
    sm = OrderProcessing(quiet=True)

    # Common preamble
    sm.submit()
    sm.approve()
    sm.start()
    sm.reserve()
    sm.mark_unavailable()



def test_path_track_inventory_08_allocated():
    """Track 'inventory' path 8: checking → reserved → allocated"""
    sm = OrderProcessing(quiet=True)

    # Common preamble
    sm.submit()
    sm.approve()
    sm.start()
    sm.reserve()
    sm.allocate()

    assert sm._inventory_reserved
    assert sm._inventory_allocated


def test_path_track_payment_01_declined():
    """Track 'payment' path 1: pay_hold → processing → declined"""
    sm = OrderProcessing(quiet=True)

    # Common preamble
    sm.submit()
    sm.approve()
    sm.start()
    # Guard flags for 'process_payment'
    sm._inventory_reserved = True
    sm.process_payment()
    sm.decline()



def test_path_track_payment_02_authorized():
    """Track 'payment' path 2: pay_hold → processing → authorized"""
    sm = OrderProcessing(quiet=True)

    # Common preamble
    sm.submit()
    sm.approve()
    sm.start()
    # Guard flags for 'process_payment'
    sm._inventory_reserved = True
    sm.process_payment()
    sm.authorize()

    assert sm._payment_authorized


def test_path_track_shipping_01_acknowledged():
    """Track 'shipping' path 1: ship_hold → preparing → ready → in_transit → delivered → acknowledged"""
    sm = OrderProcessing(quiet=True)

    # Common preamble
    sm.submit()
    sm.approve()
    sm.start()
    # Guard flags for 'begin_shipping'
    sm._inventory_allocated = True
    sm._payment_authorized = True
    sm.begin_shipping()
    sm.mark_ready()
    sm.dispatch()
    sm.deliver()
    sm.acknowledge()


