"""
Auto-generated by smcheck.testgen for OrderProcessing.

DO NOT edit manually — regenerate with:
  python -m smcheck testgen --output <dir>
"""
from __future__ import annotations

from machine import OrderProcessing



def _active(sm, state_id: str) -> bool:
    """Return True when *state_id* is part of the current active configuration."""
    return any(s.id == state_id for s in sm.configuration)


# ========================================================================
# Transition-level tests (one per named edge)
# ========================================================================

def test_transition_backordered__stock_available__reserved():
    """Transition: backordered --[stock_available]--> reserved"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'backordered'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm.backorder()
    # Fire 'stock_available'
    sm.stock_available()

    assert sm._inventory_reserved


def test_transition_backordered__request_approval__stock_review():
    """Transition: backordered --[request_approval]--> stock_review"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'backordered'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm.backorder()
    # Fire 'request_approval'
    sm.request_approval()



def test_transition_checking__reserve__reserved():
    """Transition: checking --[reserve]--> reserved"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'checking'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    # Fire 'reserve'
    sm.reserve()

    assert sm._inventory_reserved


def test_transition_checking__backorder__backordered():
    """Transition: checking --[backorder]--> backordered"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'checking'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    # Fire 'backorder'
    sm.backorder()



def test_transition_checking__mark_partial__partial_stock():
    """Transition: checking --[mark_partial]--> partial_stock"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'checking'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    # Fire 'mark_partial'
    sm.mark_partial()



def test_transition_delivered__acknowledge__acknowledged():
    """Transition: delivered --[acknowledge]--> acknowledged"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'delivered'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm._inventory_allocated = True
    sm._payment_authorized = True
    sm.begin_shipping()
    sm.mark_ready()
    sm.dispatch()
    sm.deliver()
    # Fire 'acknowledge'
    sm.acknowledge()



def test_transition_fulfillment__pause__on_hold():
    """Transition: fulfillment --[pause]--> on_hold"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'fulfillment'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    # Set guard flags for 'pause'
    sm._dispatched = False
    # Fire 'pause'
    sm.pause()

    assert _active(sm, 'on_hold')


def test_transition_fulfillment__suspend__ops_hold():
    """Transition: fulfillment --[suspend]--> ops_hold"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'fulfillment'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    # Set guard flags for 'suspend'
    sm._dispatched = False
    sm._ops_authorized = True
    # Fire 'suspend'
    sm.suspend()

    assert _active(sm, 'ops_hold')


def test_transition_fulfillment__fail__failed():
    """Transition: fulfillment --[fail]--> failed"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'fulfillment'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    # Fire 'fail'
    sm.fail()

    assert _active(sm, 'failed')


def test_transition_fulfillment__complete__success():
    """Transition: fulfillment --[complete]--> success"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'fulfillment'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    # Set guard flags for 'complete'
    sm._inventory_allocated = True
    sm._payment_authorized = True
    sm._shipping_acknowledged = True
    # Fire 'complete'
    sm.complete()

    assert _active(sm, 'success')


def test_transition_fulfillment__cancel__cancelled():
    """Transition: fulfillment --[cancel]--> cancelled"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'fulfillment'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    # Set guard flags for 'cancel'
    sm._dispatched = False
    # Fire 'cancel'
    sm.cancel()

    assert _active(sm, 'cancelled')


def test_transition_idle__submit__validation():
    """Transition: idle --[submit]--> validation"""
    sm = OrderProcessing(quiet=True)

    # Fire 'submit'
    sm.submit()

    assert _active(sm, 'validation')


def test_transition_idle__cancel__cancelled():
    """Transition: idle --[cancel]--> cancelled"""
    sm = OrderProcessing(quiet=True)

    # Set guard flags for 'cancel'
    sm._dispatched = False
    # Fire 'cancel'
    sm.cancel()

    assert _active(sm, 'cancelled')


def test_transition_in_transit__deliver__delivered():
    """Transition: in_transit --[deliver]--> delivered"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'in_transit'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm._inventory_allocated = True
    sm._payment_authorized = True
    sm.begin_shipping()
    sm.mark_ready()
    sm.dispatch()
    # Fire 'deliver'
    sm.deliver()



def test_transition_on_hold__resume__h():
    """Transition: on_hold --[resume]--> h"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'on_hold'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm._dispatched = False
    sm.pause()
    # Fire 'resume'
    sm.resume()



def test_transition_on_hold__cancel__cancelled():
    """Transition: on_hold --[cancel]--> cancelled"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'on_hold'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm._dispatched = False
    sm.pause()
    # Set guard flags for 'cancel'
    sm._dispatched = False
    # Fire 'cancel'
    sm.cancel()

    assert _active(sm, 'cancelled')


def test_transition_ops_hold__release__h():
    """Transition: ops_hold --[release]--> h"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'ops_hold'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm._dispatched = False
    sm._ops_authorized = True
    sm.suspend()
    # Set guard flags for 'release'
    sm._ops_authorized = True
    # Fire 'release'
    sm.release()



def test_transition_ops_hold__cancel__cancelled():
    """Transition: ops_hold --[cancel]--> cancelled"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'ops_hold'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm._dispatched = False
    sm._ops_authorized = True
    sm.suspend()
    # Set guard flags for 'cancel'
    sm._dispatched = False
    # Fire 'cancel'
    sm.cancel()

    assert _active(sm, 'cancelled')


def test_transition_partial_stock__accept_partial__allocated():
    """Transition: partial_stock --[accept_partial]--> allocated"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'partial_stock'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm.mark_partial()
    # Fire 'accept_partial'
    sm.accept_partial()

    assert sm._inventory_reserved
    assert sm._inventory_allocated


def test_transition_pay_hold__process_payment__processing():
    """Transition: pay_hold --[process_payment]--> processing"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'pay_hold'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    # Set guard flags for 'process_payment'
    sm._inventory_reserved = True
    # Fire 'process_payment'
    sm.process_payment()



def test_transition_preparing__mark_ready__ready():
    """Transition: preparing --[mark_ready]--> ready"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'preparing'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm._inventory_allocated = True
    sm._payment_authorized = True
    sm.begin_shipping()
    # Fire 'mark_ready'
    sm.mark_ready()



def test_transition_processing__authorize__authorized():
    """Transition: processing --[authorize]--> authorized"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'processing'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm._inventory_reserved = True
    sm.process_payment()
    # Fire 'authorize'
    sm.authorize()

    assert sm._payment_authorized


def test_transition_processing__decline__declined():
    """Transition: processing --[decline]--> declined"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'processing'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm._inventory_reserved = True
    sm.process_payment()
    # Fire 'decline'
    sm.decline()



def test_transition_ready__dispatch__in_transit():
    """Transition: ready --[dispatch]--> in_transit"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'ready'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm._inventory_allocated = True
    sm._payment_authorized = True
    sm.begin_shipping()
    sm.mark_ready()
    # Fire 'dispatch'
    sm.dispatch()



def test_transition_reserved__allocate__allocated():
    """Transition: reserved --[allocate]--> allocated"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'reserved'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm.reserve()
    # Fire 'allocate'
    sm.allocate()

    assert sm._inventory_reserved
    assert sm._inventory_allocated


def test_transition_reserved__mark_unavailable__out_of_stock():
    """Transition: reserved --[mark_unavailable]--> out_of_stock"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'reserved'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm.reserve()
    # Fire 'mark_unavailable'
    sm.mark_unavailable()



def test_transition_reviewing__approve__approved():
    """Transition: reviewing --[approve]--> approved"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'reviewing'
    sm.submit()
    # Fire 'approve'
    sm.approve()

    assert _active(sm, 'approved')


def test_transition_reviewing__reject__rejected():
    """Transition: reviewing --[reject]--> rejected"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'reviewing'
    sm.submit()
    # Fire 'reject'
    sm.reject()

    assert _active(sm, 'rejected')


def test_transition_ship_hold__begin_shipping__preparing():
    """Transition: ship_hold --[begin_shipping]--> preparing"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'ship_hold'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    # Set guard flags for 'begin_shipping'
    sm._inventory_allocated = True
    sm._payment_authorized = True
    # Fire 'begin_shipping'
    sm.begin_shipping()



def test_transition_stock_review__approve_partial__reserved():
    """Transition: stock_review --[approve_partial]--> reserved"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'stock_review'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm.backorder()
    sm.request_approval()
    # Fire 'approve_partial'
    sm.approve_partial()

    assert sm._inventory_reserved


def test_transition_stock_review__decline_partial__out_of_stock():
    """Transition: stock_review --[decline_partial]--> out_of_stock"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'stock_review'
    sm.submit()
    sm.approve()
    sm._validation_approved = True
    sm.start()
    sm.backorder()
    sm.request_approval()
    # Fire 'decline_partial'
    sm.decline_partial()



def test_transition_validation__start__fulfillment():
    """Transition: validation --[start]--> fulfillment"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'validation'
    sm.submit()
    # Set guard flags for 'start'
    sm._validation_approved = True
    # Fire 'start'
    sm.start()

    assert _active(sm, 'fulfillment')


def test_transition_validation__cancel__cancelled():
    """Transition: validation --[cancel]--> cancelled"""
    sm = OrderProcessing(quiet=True)

    # Reach source state 'validation'
    sm.submit()
    # Set guard flags for 'cancel'
    sm._dispatched = False
    # Fire 'cancel'
    sm.cancel()

    assert _active(sm, 'cancelled')

